name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: github-metrics
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
            filename: metrics-isocalendar.svg
            token: ${{ secrets.METRICS_TOKEN }}
            base: ""
            plugin_isocalendar: yes
            plugin_isocalendar_duration: full-year
            config_timezone: Europe/Oslo