name: Metrics
on:
  schedule: [{cron: "0 0 * * 0"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: github-metrics
    permissions:
      contents: write
    steps:
      - name: "Habits facts"
        uses: lowlighter/metrics@latest
        with:
            filename: metrics-habits-facts.svg
            token: ${{ secrets.METRICS_TOKEN }}
            base: ""
            plugin_habits: yes
            plugin_habits_facts: yes
            plugin_habits_charts: no
            config_timezone: Europe/Oslo
      # - name: "Habits charts"
      #   uses: lowlighter/metrics@latest
      #   with:
      #     filename: metrics-habits-charts.svg
      #     token: ${{ secrets.METRICS_TOKEN }}
      #     base: ""
      #     plugin_habits: yes
      #     plugin_habits_facts: no
      #     plugin_habits_charts: yes
      #     config_timezone: Europe/Oslo